!function(){requirejs.config({baseUrl:'http://static.qyer.com/m',map:{'*':{'css':'basic/js/require-css'}}});!function(){if(window.qyerUtil){return;}
window.qyerUtil={EVENT:{CLICK:'click'},_head:null,_getHead:function(){if(!this._head){this._head=document.getElementsByTagName("head")[0];}
return this._head;},loadCss:function(aFilePath,aAsync){if(aAsync===false){this.insertStyle($.ajax({url:aFilePath,async:false}).responseText);}else{$('<link rel="stylesheet" type="text/css" />').attr("href",aFilePath).appendTo(this._getHead());}},insertStyle:function(aStr){var nod=document.createElement("style");nod.type="text/css";if(nod.styleSheet){nod.styleSheet.cssText=aStr;}else{nod.innerHTML=aStr;}
this._getHead().appendChild(nod);nod=null;},sliceArguments:function(aArgument,aIndex){var ps=[];for(var i=aIndex;i<aArgument.length;i++){ps.push(aArgument[i]);};return ps;},isMobile:function(){var uA=navigator.userAgent;return(uA.match(/Android/i)||uA.indexOf('iPhone')!=-1||uA.indexOf('iPad')!=-1);},getWordLen:function(aValue,g){function byteLength(b){if(typeof b=="undefined"){return 0;}
var a=b.match(/[^\x00-\x80]/g);return(b.length+(!a?0:a.length));}
function doublebyte(str){return str.replace(/[^\x00-\xff]/g,'*');}
if(g){aValue=doublebyte(aValue);}
return byteLength($.trim(aValue));},subStr:function(aStr,aLen){var char_length=0,son_str,sub_len;for(var i=0;i<aStr.length;i++){son_str=aStr.charAt(i);encodeURI(son_str).length>2?char_length+=1:char_length+=0.5;if(char_length>=aLen){sub_len=char_length==aLen?i+1:i;return aStr.substr(0,sub_len);break;}}
return aStr;},runOneInPeriodOfTime:function(aFun,aTimer){var timer;return function(){window.clearTimeout(timer);timer=window.setTimeout(function(){aFun();},aTimer||300);};},__bodyTouchmoveFun__:function(aEvt){aEvt.preventDefault();},disableBodyScroll:function(){document.body.addEventListener('touchmove',this.__bodyTouchmoveFun__,false);},enableBodyScroll:function(){document.body.removeEventListener('touchmove',this.__bodyTouchmoveFun__);},renderTemplate:function(tmpl,data){if(!data)return false;return tmpl.replace(/{{(\/?)(\w+|.)(?:\((.*?)\))?(?: (.*?))?}}/g,function(match){var key=match.slice(4,-2).replace(/(^\s*)|(\s*$)/g,"");return(key in data)?data[key]:"";});},ajax:function(aOption){var _startDate,_duringTime,dataProcess;_startDate=aOption.minResponseTime?new Date():null;dataProcess=function(aJSON){if(typeof aJSON.error_code=='undefined'){try{aJSON.error_code=aJSON.error;aJSON.result=aJSON.result;if(aJSON.error_code!=0){aJSON.data=aJSON.data||{};aJSON.data.msg=aJSON.msg;}}catch(err){}}
if(aJSON.error_code==0){if(typeof(aJSON.data)=='undefined'){aJSON.data=aOption.__defaultData__;}
aOption.onCallSuccessBefore&&aOption.onCallSuccessBefore(aJSON);aOption.onSuccess&&aOption.onSuccess(aJSON);aOption.onCallSuccessAfter&&aOption.onCallSuccessAfter(aJSON);}else{aOption.onError&&aOption.onError(aJSON);}};if(aOption.testData){if(typeof(aOption.testData.data)=='undefined'){aOption.testData.data=aOption.__defaultData__;}
setTimeout(function(){dataProcess(aOption.testData);},(aOption.minResponseTime||200));return;}
var _host=window.location.host,_url=aOption.url||aOption.posturl,_data=aOption.data,_dataType='json';if(/static.qyer.com/.test(_host)===true){var id;_data=$.extend({},_data,{__qFED__:aOption.__qFED__});if(aOption.__qFED__&&aOption.__qFED__.id){id=aOption.__qFED__.id;aOption.type="GET";}
_url='http://fe.2b6.me:3000/service/api/'+id;_dataType='jsonp';api=null;}
var _ajax=$.ajax({type:aOption.type||"POST",url:_url,dataType:_dataType,data:_data,cache:aOption.cache||false,success:function(aJSON){if(_startDate){_duringTime=new Date()-_startDate;setTimeout(function(){dataProcess.call(null,aJSON);},(_duringTime>aOption.minResponseTime?0:aOption.minResponseTime-_duringTime));}else{dataProcess.call(null,aJSON);}
_startDate=_duringTime=null;},error:function(aXhr,aInfo){aOption.onError&&aOption.onError({"error_code":-1,"__server_error__":true,"__server_status__":_ajax.statusText,"result":"error","data":{"msg":aInfo||{}}});}});return _ajax;},doAjax:function(aOption){this.ajax(aOption);},doTrackCode:function(aCode){var id='__dotarckcodebutton__';if(!document.getElementById(id)){$('<button id="'+id+'" style="display:none;">dotarckcodebutton</button>').appendTo(document.body);}
$('#'+id).attr('data-bn-ipg',aCode).trigger('click');id=null;},ajaxFillter:function(data,xhr,settings,deferred){if(window.location.href.indexOf('http://m.qyer.com/plan')==0){return;}
if(typeof(data)=='object'){if(data.extra&&data.extra.code){switch(data.extra.code|0){case 1:window.qyerUtil.showAntiSpam(data.extra.msg);break;}}}},showAntiSpam:function(aText){requirejs(['common/component/antiSpam/antiSpam'],function(m){m.show(aText);});},getUrlParam:function(aKey,aURL){var reg=new RegExp("(^|&)"+aKey+"=([^&]*)(&|$)");var url;if(aURL){var i=aURL.indexOf('?');i!=-1&&(url=aURL.substr(aURL.indexOf('?')+1));}else{url=window.location.search.substr(1);}
var r=url.match(reg);if(r!=null)return unescape(r[2]);return null;},isLogin:function(){return!!(window.QYER&&window.QYER.uid);},doLogin:function(referrer){referrer=referrer||window.location.href;referrer=encodeURIComponent(decodeURIComponent(referrer));window.location.href="http://m.qyer.com/login/login.php?from_url="+referrer;}};}();!function(){if(qyerUtil.isMobile()){qyerUtil.EVENT.CLICK='tap';}}();!function(){function ex(aObj,aEx){for(var key in aEx){aObj[key]=aEx[key];}}
ex(Date.prototype,{qGetWeekStr:function(){return'星期'+["日","一","二","三","四","五","六"][this.getDay()];},qAddDate:function(aNum){this.setDate(this.getDate()+aNum);return this;},qToString:function(aSplit){var str=[this.getFullYear(),this.getMonth()+1,this.getDate()];return str.join(aSplit||'-');}});ex(String.prototype,{qToDate:function(aSplit){var s=this.split(aSplit||'-');s=[s[0]|0,(s[1]|0)-1,s[2]|0];var d=new Date(s[0],s[1],s[2]);s.length=0;s=null;return d;},qToIntFixed:function(){var n=this|0;return n<10?'0'+n:n.toString();},qToHTML:function(){return this.replace(/</gi,"&lt;").replace(/>/gi,"&gt;").replace(/\n/gi,"<br />").replace(/\t/gi,"&nbsp;&nbsp;&nbsp;&nbsp;");}});}();}();